server:
  port: ':8081'
  mode: release

database:
  server: '192.168.120.20'
  port: 3306
  user: 'root'
  password: '123456'
  database-name: 'matomo'
  pool:
    max-connection: 10
    max-idle-connection: 5
redis:
  host: '127.0.0.1'
  port: 6379
  password: '123456'
  db: 1
  pool:
    max-idle: 5
    idle-timeout: 14400

